### ISSUE TITLE
UnifiOS?

### ISSUE THREAD

**Issue by bondskin** [EpeR1/unifi-munin#1]
Hi,

Is this supposed to work with UnifiOS (e.g. UDM) as I get error messages

`2020/05/24-09:55:06 [9705]      PHP Notice:  Undefined index: head in /usr/share/munin/plugins/ubnt_unifi.php on line 30
2020/05/24-09:55:06 [9705]      PHP Warning:  Invalid argument supplied for foreach() in /usr/share/munin/plugins/ubnt_unifi.php on line 30
2020/05/24-09:55:06 [9705]      PHP Notice:  Undefined index: g_multi in /usr/share/munin/plugins/ubnt_unifi.php on line 21
2020/05/24-09:55:06 [9705]      PHP Notice:  Undefined index: g_controller in /usr/share/munin/plugins/ubnt_unifi.php on line 22
2020/05/24-09:55:06 [9705]      PHP Notice:  Undefined index: g_title in /usr/share/munin/plugins/ubnt_unifi.php on line 23
2020/05/24-09:55:06 [9705]      PHP Notice:  Undefined index: g_vlabel in /usr/share/munin/plugins/ubnt_unifi.php on line 25
2020/05/24-09:55:06 [9705]      PHP Notice:  Undefined index: g_category in /usr/share/munin/plugins/ubnt_unifi.php on line 26
2020/05/24-09:55:06 [9705]      PHP Notice:  Undefined index: g_info in /usr/share/munin/plugins/ubnt_unifi.php on line 27
2020/05/24-09:55:06 [9705]      PHP Notice:  Undefined index: head in /usr/share/munin/plugins/ubnt_unifi.php on line 30
2020/05/24-09:55:06 [9705]      PHP Warning:  Invalid argument supplied for foreach() in /usr/share/munin/plugins/ubnt_unifi.php on line 30`

**Comment by EpeR1** [comment]
The script is using a controller hostname only for grouping graphs, and does not queries the controller.
It queries directly from APs, and only via SNMP.
So I think it can be usable with any version of controller.
Submitted errors seems to be a configuration error. 
More debug info can be generated with "munin_run ubnt_unifi debug" command. (update from git is may needed before)

**Comment by bondskin** [comment]
[ubnt_debug.log](https://github.com/EpeR1/munin-unifi/files/4676973/ubnt_debug.log)

Thanks, this is the result

**Comment by EpeR1** [comment]
The RAW array is empty in debug_log, which means, the script couldn't get data from Access Points. 
It is happen, when:
- No route from munin server to APs. (Also check route to port: 161)
- No SNMP enabled on APs
- PHP module: php-snmp, php-json not installed.
- Timeout is low (Isn't enough time for data to arrive to server)

**Comment by EpeR1** [comment]
The RAW array is empty in debug_log, which means, the script couldn't get data from Access Points. 
It is happen, when:
- No route from munin server to APs. (Also check route to port: 161)
- No SNMP enabled on APs
- PHP module: php-snmp, php-json not installed.
- Timeout is low (Isn't enough time for data to arrive to server)
(I Updated the code, please check)

**Comment by EpeR1** [comment]
#Tip:
Network Route from munin server to Access Points can be tested with `snmpwalk` command, like:  
` snmpwalk -v2c -c public ap01.network.lan  'iso.3.6.1.4.1.41112' `
( `apt-get install snmp` on Debian/Ubuntu if snmp command was not found)
The result will be a large list of parameters/values from Access Point.

**Comment by bondskin** [comment]
[ubnt.log](https://github.com/EpeR1/munin-unifi/files/4680662/ubnt.log)

here is the new log file, running your test script.
I need forgot the php-snmp, but still seeing errors.
a SNMP test (snmpwalk) works

I think we are making progress but still no graphs on munin yet

**Comment by bondskin** [comment]
running "sudo munin-run ubnt_unifi debug" looks much better (with your new version and php-snmp package installed :-)

see result attached, but still no graphs on munin
[ubnt.log](https://github.com/EpeR1/munin-unifi/files/4680731/ubnt.log)

**Comment by bondskin** [comment]
running the node command via shell, I get values

"sudo munin-run ubnt_unifi
multigraph unifi_radio_192_168_2_1
unifi_2g_clients.value 7
unifi_5g_clients.value 13
unifi_sum_clients.value 20
unifi__transwarp_.value 20


multigraph unifi_radio_192_168_2_1.batman_ip
unifi_2g_clients.value 2
unifi_5g_clients.value 6
unifi_sum_clients.value 8
unifi__transwarp_.value 8


multigraph unifi_radio_192_168_2_1.dome_ip
unifi_2g_clients.value 5
unifi_5g_clients.value 7
unifi_sum_clients.value 12
unifi__transwarp_.value 12


multigraph unifi_netw_192_168_2_1
unifi_rx_2g.value 13030
unifi_tx_2g.value 746190
unifi_rx_5g.value 1544234"

**Comment by bondskin** [comment]
munin does not list this plugin... I don't understand that. 
The plugin is executable and runs fine if I use the munin-run command.
But it does not even produce a log entry when scheduled 

pi@raspberrypiwatch:/usr/share/munin/plugins $ telnet localhost 4949
Trying ::1...
Connected to localhost.
Escape character is '^]'.
# munin node at raspberrypiwatch.ip
list
acpi cpu cpuspeed df dump1090_cpu dump1090_messages dump1090_quality dump1090_signal dump1090_tracks http_loadtime if_err_eth0 if_err_wlan0 if_eth0 if_wlan0 load memory munin_stats munin_update netstat ntpdate_0.europe.pool.ntp.org pihole_cache pihole_clients pihole_queries ping_google.de processes swap threads timesync_status unbound_munin_by_flags unbound_munin_by_rcode unbound_munin_by_type unbound_munin_histogram unbound_munin_hits unbound_munin_memory unbound_munin_queue uptime users

**Comment by bondskin** [comment]
got it, finally.
it was a config error in the munin.conf vs munin-node where the controller name was not identical.

thanks!

**Comment by EpeR1** [comment]
Yes should `env.controller` hostname be same as in munin.conf `[controller_hostname]`setting.
Munin-node doesn't list this plugin on telnet, because it makes a virtual node,  
but if you check `fetch ubnt_unifi` after telnet, the result should be like a "normal" plugin's result.  
Submitted debug log shows settings are correct.

**Comment by EpeR1** [comment]
## Tip nr.2:
If you set a name or location to Access Points (On unifi configuration site), the script will use that, instead of IP address, or "Unknown" label, on graph's title.
(Related with debug.log: `[iso.3.6.1.2.1.1.6.0] => STRING: "Unknown"`  Change this to "office" or "garden" or location, or something else. )

**Comment by EpeR1** [comment]
## Tip nr.2:
If you set a name or location to Access Points ("Alias" on unifi configuration site), the script will use that, instead of IP address, or "Unknown" label, on graph's title.
(Related with debug.log: `[iso.3.6.1.2.1.1.6.0] => STRING: "Unknown"` Change this to "office" or "garden" or location, or something else. )

**Comment by bondskin** [comment]
thanks, I noticed the alias. great stuff!
Also switches are detected but not plotted as a graph, might be nice enhancement for the future

The UDM (base) does not support SNMP yet, hence your plugin does deliver results, so I will wait until a future UnifiOS release brings that feature. 
All my APs (AC Pro & NanoHD) are working great with your plugin!

**Comment by EpeR1** [comment]
Plotting graphs for switches and other unifi devices are planned, but I have only AP-AC-PRO Access Points now, with cisco switches, so I don't know which SNMP rows are useful or interesting for nice graphs. 

If somebody explains me the SNMP structure of switches, I can update the code for supporting switches.
(And/Or pull requests are welcome.)

**Comment by EpeR1** [comment]
Plotting graphs for switches and other unifi devices are planned, but I have only AP-AC-PRO Access Points now, with cisco switches, so I don't know which SNMP rows are useful or interesting for nice graphs.

If somebody explains me the SNMP structure of switches, I can update the code for supporting switches.
(And/Or pull requests are welcomed.)
